import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { AppLayout } from "@/components/AppLayout";
import { PageHeader } from "@/components/PageHeader";
import { StatCard } from "@/components/StatCard";
import { Panel } from "@/components/Panel";
import { Gavel, CheckCircle2, XCircle, Clock, Search, Filter } from "lucide-react";
import { REPRESENTACOES, REPRESENTACOES_TIPO } from "@/data/sipi";
import { formatRepresentacaoId, loadRepresentacoes, saveRepresentacoes } from "@/lib/casesLocalState";

export const Route = createFileRoute("/representacoes")({ component: Representacoes });
const statusTone: Record<string, string> = { "Cumprida (Positiva)": "bg-success/15 text-success border-success/30", Deferida: "bg-success/15 text-success border-success/30", Indeferida: "bg-destructive/15 text-destructive border-destructive/30", "Em análise": "bg-info/15 text-info border-info/30", "Aguardando Análise Judicial": "bg-warning/15 text-warning border-warning/30" };
const normalizeText = (v?: string)=> (v??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().trim();

function Representacoes() {
  const navigate = useNavigate();
  const [searchTerm, setSearchTerm] = useState("");
  const [representacoes, setRepresentacoes] = useState(loadRepresentacoes);
  useEffect(()=>{saveRepresentacoes(representacoes);},[representacoes]);
  const filteredRepresentacoes = useMemo(() => { const s = normalizeText(searchTerm); if (!s) return representacoes; return representacoes.filter((r) => [formatRepresentacaoId(r.id), r.ppe, r.vitima, r.investigado, r.tipo, r.processo, r.status].map((value) => normalizeText(String(value ?? ""))).some((value) => value.includes(s))); }, [representacoes, searchTerm]);

  return <AppLayout><PageHeader title="Representações Judiciais" subtitle="Medidas requeridas ao Poder Judiciário" showActions={false} />
  <div className="mb-6 flex justify-end"><Link to="/nova-representacao" className="inline-flex items-center gap-2 bg-primary text-primary-foreground px-4 py-2.5 rounded-lg text-sm font-semibold">Cadastrar Representação</Link></div>
  <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6"><StatCard label="TOTAL" value={REPRESENTACOES.total} hint="Representações" icon={Gavel} tone="info" /><StatCard label="DEFERIMENTO" value={`${REPRESENTACOES.taxaDeferimento}%`} hint={`${REPRESENTACOES.total - REPRESENTACOES.indeferidas} deferidas`} icon={CheckCircle2} tone="success" /><StatCard label="CUMPRIDAS" value={REPRESENTACOES.cumpridas} hint={`${REPRESENTACOES.taxaCumprimento}% taxa`} icon={CheckCircle2} tone="primary" /><StatCard label="INDEFERIDAS" value={REPRESENTACOES.indeferidas} hint="Não acolhidas" icon={XCircle} tone="destructive" /></div>
  <div className="grid grid-cols-1 lg:grid-cols-3 gap-5 mb-6"><Panel title="POR TIPO DE REPRESENTAÇÃO" accent="success" className="lg:col-span-2"><table className="w-full text-sm"><thead className="text-[10px] tracking-[0.15em] text-muted-foreground"><tr className="border-b border-border"><th className="text-left py-2 font-bold">TIPO</th><th className="text-right py-2 font-bold">TOTAL</th><th className="text-right py-2 font-bold">DEFERIDAS</th><th className="text-right py-2 font-bold">CUMPRIDAS</th><th className="text-right py-2 font-bold">% SUCESSO</th></tr></thead><tbody>{REPRESENTACOES_TIPO.map((t)=>{const pct=t.total?Math.round((t.deferidas/t.total)*100):0;return <tr key={t.tipo} className="border-b border-border/50"><td className="py-3 font-medium">{t.tipo}</td><td className="py-3 text-right tabular-nums">{t.total}</td><td className="py-3 text-right tabular-nums text-success">{t.deferidas}</td><td className="py-3 text-right tabular-nums text-info">{t.cumpridas}</td><td className="py-3 text-right tabular-nums font-semibold">{pct}%</td></tr>;})}</tbody></table></Panel><Panel title="STATUS GERAL" accent="warning" icon={<Clock className="h-4 w-4 text-warning" />}><ul className="space-y-3 text-sm"><li className="flex items-center justify-between"><span>Total de pedidos</span><span>{REPRESENTACOES.total}</span></li></ul></Panel></div>
  <div className="bg-card border border-border rounded-xl overflow-hidden"><div className="p-4 border-b border-border bg-background/50"><div className="flex flex-col md:flex-row gap-3"><div className="flex-1 relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" /><input placeholder="Buscar por ID, PPE, vítima, investigado, tipo, processo ou status..." value={searchTerm} onChange={(e) => setSearchTerm(e.target.value)} className="w-full bg-card border border-border rounded-lg pl-10 pr-4 py-2.5 text-sm" /></div><button className="inline-flex items-center gap-2 border border-border bg-card px-4 py-2.5 rounded-lg text-sm hover:bg-accent"><Filter className="h-4 w-4" /> Filtros</button></div></div>
  <div className="overflow-auto"><table className="w-full text-sm min-w-[1200px]"><thead className="bg-muted/40 text-[10px] tracking-[0.15em] text-muted-foreground"><tr><th className="text-left px-4 py-3 font-bold">ID</th><th className="text-left px-4 py-3 font-bold">PPE</th><th className="text-left px-4 py-3 font-bold">VÍTIMA</th><th className="text-left px-4 py-3 font-bold">INVESTIGADO</th><th className="text-left px-4 py-3 font-bold">TIPO</th><th className="text-left px-4 py-3 font-bold">PROCESSO</th><th className="text-left px-4 py-3 font-bold">DATA</th><th className="text-left px-4 py-3 font-bold">STATUS</th><th className="text-right px-4 py-3 font-bold">AÇÃO</th></tr></thead><tbody>{filteredRepresentacoes.map((r) => <tr key={r.localRef} className="border-t border-border hover:bg-muted/20"><td className="px-4 py-3 font-semibold">{formatRepresentacaoId(r.id)}</td><td className="px-4 py-3 font-semibold">{r.ppe}</td><td className="px-4 py-3 text-xs">{r.vitima}</td><td className="px-4 py-3 text-xs">{r.investigado}</td><td className="px-4 py-3 text-xs">{r.tipo}</td><td className="px-4 py-3 text-xs">{r.processo}</td><td className="px-4 py-3 text-xs">{r.data}</td><td className="px-4 py-3"><span className={`text-[10px] font-bold px-2 py-1 rounded border ${statusTone[r.status] ?? "bg-muted/30 text-muted-foreground border-border"}`}>{r.status}</span></td><td className="px-4 py-3 text-right"><button onClick={() => navigate({ to: "/representacoes/$representacaoId", params: { representacaoId: r.id } })} className="rounded-md border border-info/30 bg-info/10 px-2.5 py-1 text-[11px] font-semibold text-info">Abrir</button></td></tr>)}</tbody></table></div></div></AppLayout>;
}
