import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { AppLayout } from "@/components/AppLayout";
import { formatRepresentacaoId, loadRepresentacoes, saveRepresentacoes } from "@/lib/casesLocalState";

export const Route = createFileRoute("/representacoes/$representacaoId")({ component: DetalheRepresentacao });

function DetalheRepresentacao() {
  const { representacaoId } = Route.useParams();
  const navigate = useNavigate();
  const item = loadRepresentacoes().find((r) => r.id === representacaoId);
  if (!item) return <AppLayout>Representação não encontrada.</AppLayout>;
  const remove = () => { if (!confirm("Deseja remover esta representação? No sistema final, esta ação deverá ser registrada em auditoria.")) return; saveRepresentacoes(loadRepresentacoes().filter((r) => r.id !== item.id)); navigate({ to: "/representacoes" }); };
  return <AppLayout><div className="space-y-6"><header className="rounded-xl border border-border bg-card p-5 flex flex-col gap-4 lg:flex-row lg:justify-between"><div><Link to="/representacoes" className="text-xs border border-border rounded-md px-3 py-1.5 inline-block mb-3">← Voltar para lista</Link><h1 className="text-2xl font-extrabold">Representação {formatRepresentacaoId(item.id)}</h1><p className="text-sm text-muted-foreground">PPE relacionado: {item.ppe} • Última atualização: {item.data}</p><span className="mt-2 inline-block px-2 py-1 text-[10px] rounded border border-info/30 bg-info/10">{item.status}</span></div><div className="flex gap-2"><button onClick={()=>window.print()} className="px-3 py-2 text-xs rounded-md border border-border">Imprimir</button><button onClick={()=>navigate({to:"/representacoes/$representacaoId/editar",params:{representacaoId:item.id}})} className="px-3 py-2 text-xs rounded-md border border-border">Editar</button><button onClick={remove} className="px-3 py-2 text-xs rounded-md border border-destructive/30 bg-destructive/10 text-destructive">Excluir</button></div></header>
  <section className="grid md:grid-cols-2 gap-4">{[["Identificação da Representação",[["ID",formatRepresentacaoId(item.id)],["PPE relacionado",item.ppe],["Nº Processo Judicial",item.processo],["Tipo",item.tipo],["Data",item.data],["Responsável","—"]]],["Pessoas Envolvidas",[["Vítima",item.vitima],["Investigado / Representado",item.investigado],["Autor preso?","Não informado"]]],["Fundamentação e Finalidade",[["Resumo dos fatos","—"],["Fundamentação da medida","—"],["Objetivo","—"],["Diligências relacionadas","—"]]],["Tramitação Judicial",[["Status",item.status],["Data envio","—"],["Data da decisão","—"],["Observações da decisão","—"]]],["Cumprimento da Medida",[["Data cumprimento","—"],["Equipe responsável","—"],["Resultado","—"],["Observações","—"]]],["Controle Interno",[["Prioridade operacional","—"],["Pedido sigiloso?","—"],["Observações internas","—"]]]].map(([title,items])=><article key={String(title)} className="rounded-xl border border-border bg-card p-4"><h2 className="text-xs tracking-[0.2em] text-primary font-bold mb-3 uppercase">{String(title)}</h2><div className="space-y-2">{(items as string[][]).map(([k,v])=><p key={k} className="text-sm"><span className="text-muted-foreground">{k}: </span>{v||"—"}</p>)}</div></article>)}</section></div></AppLayout>;
}
