/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AguardandoAutorizacaoRouteImport } from './routes/aguardando-autorizacao'
import { Route as AlertasRouteImport } from './routes/alertas'
import { Route as AuditoriaRouteImport } from './routes/auditoria'
import { Route as CriarContaRouteImport } from './routes/criar-conta'
import { Route as CvliComparativoRouteImport } from './routes/cvli-comparativo'
import { Route as EstatisticasRouteImport } from './routes/estatisticas'
import { Route as InqueritosRouteImport } from './routes/inqueritos'
import { Route as LocalidadesRouteImport } from './routes/localidades'
import { Route as LocalizacaoRouteImport } from './routes/localizacao'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ModulosRouteImport } from './routes/modulos'
import { Route as NovaRepresentacaoRouteImport } from './routes/nova-representacao'
import { Route as NovoCasoRouteImport } from './routes/novo-caso'
import { Route as ObjetosRouteImport } from './routes/objetos'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as RepresentacoesRouteImport } from './routes/representacoes'
import { Route as VeiculosRouteImport } from './routes/veiculos'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AgendaIndexRouteImport } from './routes/agenda.index'
import { Route as AgendaAgendamentoIdRouteImport } from './routes/agenda.$agendamentoId'
import { Route as AgendaCronogramaRouteImport } from './routes/agenda.cronograma'
import { Route as AgendaNovoRouteImport } from './routes/agenda.novo'
import { Route as AlertasModuloRouteImport } from './routes/alertas.$modulo'
import { Route as InqueritosCaseIdRouteImport } from './routes/inqueritos.$caseId'
import { Route as LocalizacaoIndexRouteImport } from './routes/localizacao.index'
import { Route as LocalizacaoEnderecosRouteImport } from './routes/localizacao.enderecos'
import { Route as LocalizacaoPessoasRouteImport } from './routes/localizacao.pessoas'
import { Route as LocalizacaoRotasRouteImport } from './routes/localizacao.rotas'
import { Route as MockupsLocalizacaoOperacionalRouteImport } from './routes/mockups.localizacao-operacional'
import { Route as ObjetosIndexRouteImport } from './routes/objetos.index'
import { Route as ObjetosObjectIdRouteImport } from './routes/objetos.$objectId'
import { Route as ObjetosNovoRouteImport } from './routes/objetos.novo'
import { Route as ObjetosTodosRouteImport } from './routes/objetos.todos'
import { Route as RepresentacoesRepresentacaoIdRouteImport } from './routes/representacoes.$representacaoId'
import { Route as VeiculosIndexRouteImport } from './routes/veiculos.index'
import { Route as VeiculosVehicleIdRouteImport } from './routes/veiculos.$vehicleId'
import { Route as VeiculosAdulteradosRouteImport } from './routes/veiculos.adulterados'
import { Route as VeiculosApreendidosRouteImport } from './routes/veiculos.apreendidos'
import { Route as VeiculosAutomoveisRouteImport } from './routes/veiculos.automoveis'
import { Route as VeiculosBicicletasRouteImport } from './routes/veiculos.bicicletas'
import { Route as VeiculosCaminhoesRouteImport } from './routes/veiculos.caminhoes'
import { Route as VeiculosLiberadosRouteImport } from './routes/veiculos.liberados'
import { Route as VeiculosMotocicletasRouteImport } from './routes/veiculos.motocicletas'
import { Route as VeiculosNovoRouteImport } from './routes/veiculos.novo'
import { Route as VeiculosOnibusRouteImport } from './routes/veiculos.onibus'
import { Route as VeiculosOutrosRouteImport } from './routes/veiculos.outros'
import { Route as VeiculosRecuperadosRouteImport } from './routes/veiculos.recuperados'
import { Route as VeiculosRelatoriosRouteImport } from './routes/veiculos.relatorios'
import { Route as VeiculosTodosRouteImport } from './routes/veiculos.todos'
import { Route as AdminUsuariosUserIdRouteImport } from './routes/admin.usuarios.$userId'
import { Route as AgendaEditarAgendamentoIdRouteImport } from './routes/agenda.editar.$agendamentoId'
import { Route as InqueritosCaseIdEditarRouteImport } from './routes/inqueritos.$caseId.editar'
import { Route as ObjetosObjectIdEditarRouteImport } from './routes/objetos.$objectId.editar'
import { Route as RepresentacoesRepresentacaoIdEditarRouteImport } from './routes/representacoes.$representacaoId.editar'
import { Route as VeiculosVehicleIdEditarRouteImport } from './routes/veiculos.$vehicleId.editar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AguardandoAutorizacaoRoute = AguardandoAutorizacaoRouteImport.update({
  id: '/aguardando-autorizacao',
  path: '/aguardando-autorizacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertasRoute = AlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditoriaRoute = AuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarContaRoute = CriarContaRouteImport.update({
  id: '/criar-conta',
  path: '/criar-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const CvliComparativoRoute = CvliComparativoRouteImport.update({
  id: '/cvli-comparativo',
  path: '/cvli-comparativo',
  getParentRoute: () => rootRouteImport,
} as any)
const EstatisticasRoute = EstatisticasRouteImport.update({
  id: '/estatisticas',
  path: '/estatisticas',
  getParentRoute: () => rootRouteImport,
} as any)
const InqueritosRoute = InqueritosRouteImport.update({
  id: '/inqueritos',
  path: '/inqueritos',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalidadesRoute = LocalidadesRouteImport.update({
  id: '/localidades',
  path: '/localidades',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalizacaoRoute = LocalizacaoRouteImport.update({
  id: '/localizacao',
  path: '/localizacao',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulosRoute = ModulosRouteImport.update({
  id: '/modulos',
  path: '/modulos',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaRepresentacaoRoute = NovaRepresentacaoRouteImport.update({
  id: '/nova-representacao',
  path: '/nova-representacao',
  getParentRoute: () => rootRouteImport,
} as any)
const NovoCasoRoute = NovoCasoRouteImport.update({
  id: '/novo-caso',
  path: '/novo-caso',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjetosRoute = ObjetosRouteImport.update({
  id: '/objetos',
  path: '/objetos',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const RepresentacoesRoute = RepresentacoesRouteImport.update({
  id: '/representacoes',
  path: '/representacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const VeiculosRoute = VeiculosRouteImport.update({
  id: '/veiculos',
  path: '/veiculos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/admin/usuarios',
  path: '/admin/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaIndexRoute = AgendaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgendaRoute,
} as any)
const AgendaAgendamentoIdRoute = AgendaAgendamentoIdRouteImport.update({
  id: '/$agendamentoId',
  path: '/$agendamentoId',
  getParentRoute: () => AgendaRoute,
} as any)
const AgendaCronogramaRoute = AgendaCronogramaRouteImport.update({
  id: '/cronograma',
  path: '/cronograma',
  getParentRoute: () => AgendaRoute,
} as any)
const AgendaNovoRoute = AgendaNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AgendaRoute,
} as any)
const AlertasModuloRoute = AlertasModuloRouteImport.update({
  id: '/$modulo',
  path: '/$modulo',
  getParentRoute: () => AlertasRoute,
} as any)
const InqueritosCaseIdRoute = InqueritosCaseIdRouteImport.update({
  id: '/$caseId',
  path: '/$caseId',
  getParentRoute: () => InqueritosRoute,
} as any)
const LocalizacaoIndexRoute = LocalizacaoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocalizacaoRoute,
} as any)
const LocalizacaoEnderecosRoute = LocalizacaoEnderecosRouteImport.update({
  id: '/enderecos',
  path: '/enderecos',
  getParentRoute: () => LocalizacaoRoute,
} as any)
const LocalizacaoPessoasRoute = LocalizacaoPessoasRouteImport.update({
  id: '/pessoas',
  path: '/pessoas',
  getParentRoute: () => LocalizacaoRoute,
} as any)
const LocalizacaoRotasRoute = LocalizacaoRotasRouteImport.update({
  id: '/rotas',
  path: '/rotas',
  getParentRoute: () => LocalizacaoRoute,
} as any)
const MockupsLocalizacaoOperacionalRoute =
  MockupsLocalizacaoOperacionalRouteImport.update({
    id: '/mockups/localizacao-operacional',
    path: '/mockups/localizacao-operacional',
    getParentRoute: () => rootRouteImport,
  } as any)
const ObjetosIndexRoute = ObjetosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ObjetosRoute,
} as any)
const ObjetosObjectIdRoute = ObjetosObjectIdRouteImport.update({
  id: '/$objectId',
  path: '/$objectId',
  getParentRoute: () => ObjetosRoute,
} as any)
const ObjetosNovoRoute = ObjetosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => ObjetosRoute,
} as any)
const ObjetosTodosRoute = ObjetosTodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => ObjetosRoute,
} as any)
const RepresentacoesRepresentacaoIdRoute =
  RepresentacoesRepresentacaoIdRouteImport.update({
    id: '/$representacaoId',
    path: '/$representacaoId',
    getParentRoute: () => RepresentacoesRoute,
  } as any)
const VeiculosIndexRoute = VeiculosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VeiculosRoute,
} as any)
const VeiculosVehicleIdRoute = VeiculosVehicleIdRouteImport.update({
  id: '/$vehicleId',
  path: '/$vehicleId',
  getParentRoute: () => VeiculosRoute,
} as any)
const VeiculosAdulteradosRoute = VeiculosAdulteradosRouteImport.update({
  id: '/adulterados',
  path: '/adulterados',
  getParentRoute: () => VeiculosRoute,
} as any)
const VeiculosApreendidosRoute = VeiculosApreendidosRouteImport.update({
  id: '/apreendidos',
  path: '/apreendidos',
  getParentRoute: () => VeiculosRoute,
} as any)
const VeiculosAutomoveisRoute = VeiculosAutomoveisRouteImport.update({
  id: '/automoveis',
  path: '/automoveis',
  getParentRoute: () => VeiculosRoute,
} as any)
const VeiculosBicicletasRoute = VeiculosBicicletasRouteImport.update({
  id: '/bicicletas',
  path: '/bicicletas',
  getParentRoute: () => VeiculosRoute,
} as any)
const VeiculosCaminhoesRoute = VeiculosCaminhoesRouteImport.update({
  id: '/caminhoes',
  path: '/caminhoes',
  getParentRoute: () => VeiculosRoute,
} as any)
const VeiculosLiberadosRoute = VeiculosLiberadosRouteImport.update({
  id: '/liberados',
  path: '/liberados',
  getParentRoute: () => VeiculosRoute,
} as any)
const VeiculosMotocicletasRoute = VeiculosMotocicletasRouteImport.update({
  id: '/motocicletas',
  path: '/motocicletas',
  getParentRoute: () => VeiculosRoute,
} as any)
const VeiculosNovoRoute = VeiculosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => VeiculosRoute,
} as any)
const VeiculosOnibusRoute = VeiculosOnibusRouteImport.update({
  id: '/onibus',
  path: '/onibus',
  getParentRoute: () => VeiculosRoute,
} as any)
const VeiculosOutrosRoute = VeiculosOutrosRouteImport.update({
  id: '/outros',
  path: '/outros',
  getParentRoute: () => VeiculosRoute,
} as any)
const VeiculosRecuperadosRoute = VeiculosRecuperadosRouteImport.update({
  id: '/recuperados',
  path: '/recuperados',
  getParentRoute: () => VeiculosRoute,
} as any)
const VeiculosRelatoriosRoute = VeiculosRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => VeiculosRoute,
} as any)
const VeiculosTodosRoute = VeiculosTodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => VeiculosRoute,
} as any)
const AdminUsuariosUserIdRoute = AdminUsuariosUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AdminUsuariosRoute,
} as any)
const AgendaEditarAgendamentoIdRoute =
  AgendaEditarAgendamentoIdRouteImport.update({
    id: '/editar/$agendamentoId',
    path: '/editar/$agendamentoId',
    getParentRoute: () => AgendaRoute,
  } as any)
const InqueritosCaseIdEditarRoute = InqueritosCaseIdEditarRouteImport.update({
  id: '/editar',
  path: '/editar',
  getParentRoute: () => InqueritosCaseIdRoute,
} as any)
const ObjetosObjectIdEditarRoute = ObjetosObjectIdEditarRouteImport.update({
  id: '/editar',
  path: '/editar',
  getParentRoute: () => ObjetosObjectIdRoute,
} as any)
const RepresentacoesRepresentacaoIdEditarRoute =
  RepresentacoesRepresentacaoIdEditarRouteImport.update({
    id: '/editar',
    path: '/editar',
    getParentRoute: () => RepresentacoesRepresentacaoIdRoute,
  } as any)
const VeiculosVehicleIdEditarRoute = VeiculosVehicleIdEditarRouteImport.update({
  id: '/editar',
  path: '/editar',
  getParentRoute: () => VeiculosVehicleIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRouteWithChildren
  '/aguardando-autorizacao': typeof AguardandoAutorizacaoRoute
  '/alertas': typeof AlertasRouteWithChildren
  '/auditoria': typeof AuditoriaRoute
  '/criar-conta': typeof CriarContaRoute
  '/cvli-comparativo': typeof CvliComparativoRoute
  '/estatisticas': typeof EstatisticasRoute
  '/inqueritos': typeof InqueritosRouteWithChildren
  '/localidades': typeof LocalidadesRoute
  '/localizacao': typeof LocalizacaoRouteWithChildren
  '/login': typeof LoginRoute
  '/modulos': typeof ModulosRoute
  '/nova-representacao': typeof NovaRepresentacaoRoute
  '/novo-caso': typeof NovoCasoRoute
  '/objetos': typeof ObjetosRouteWithChildren
  '/perfil': typeof PerfilRoute
  '/representacoes': typeof RepresentacoesRouteWithChildren
  '/veiculos': typeof VeiculosRouteWithChildren
  '/admin/usuarios': typeof AdminUsuariosRouteWithChildren
  '/agenda/$agendamentoId': typeof AgendaAgendamentoIdRoute
  '/agenda/cronograma': typeof AgendaCronogramaRoute
  '/agenda/novo': typeof AgendaNovoRoute
  '/alertas/$modulo': typeof AlertasModuloRoute
  '/inqueritos/$caseId': typeof InqueritosCaseIdRouteWithChildren
  '/localizacao/enderecos': typeof LocalizacaoEnderecosRoute
  '/localizacao/pessoas': typeof LocalizacaoPessoasRoute
  '/localizacao/rotas': typeof LocalizacaoRotasRoute
  '/mockups/localizacao-operacional': typeof MockupsLocalizacaoOperacionalRoute
  '/objetos/$objectId': typeof ObjetosObjectIdRouteWithChildren
  '/objetos/novo': typeof ObjetosNovoRoute
  '/objetos/todos': typeof ObjetosTodosRoute
  '/representacoes/$representacaoId': typeof RepresentacoesRepresentacaoIdRouteWithChildren
  '/veiculos/$vehicleId': typeof VeiculosVehicleIdRouteWithChildren
  '/veiculos/adulterados': typeof VeiculosAdulteradosRoute
  '/veiculos/apreendidos': typeof VeiculosApreendidosRoute
  '/veiculos/automoveis': typeof VeiculosAutomoveisRoute
  '/veiculos/bicicletas': typeof VeiculosBicicletasRoute
  '/veiculos/caminhoes': typeof VeiculosCaminhoesRoute
  '/veiculos/liberados': typeof VeiculosLiberadosRoute
  '/veiculos/motocicletas': typeof VeiculosMotocicletasRoute
  '/veiculos/novo': typeof VeiculosNovoRoute
  '/veiculos/onibus': typeof VeiculosOnibusRoute
  '/veiculos/outros': typeof VeiculosOutrosRoute
  '/veiculos/recuperados': typeof VeiculosRecuperadosRoute
  '/veiculos/relatorios': typeof VeiculosRelatoriosRoute
  '/veiculos/todos': typeof VeiculosTodosRoute
  '/agenda/': typeof AgendaIndexRoute
  '/localizacao/': typeof LocalizacaoIndexRoute
  '/objetos/': typeof ObjetosIndexRoute
  '/veiculos/': typeof VeiculosIndexRoute
  '/admin/usuarios/$userId': typeof AdminUsuariosUserIdRoute
  '/agenda/editar/$agendamentoId': typeof AgendaEditarAgendamentoIdRoute
  '/inqueritos/$caseId/editar': typeof InqueritosCaseIdEditarRoute
  '/objetos/$objectId/editar': typeof ObjetosObjectIdEditarRoute
  '/representacoes/$representacaoId/editar': typeof RepresentacoesRepresentacaoIdEditarRoute
  '/veiculos/$vehicleId/editar': typeof VeiculosVehicleIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aguardando-autorizacao': typeof AguardandoAutorizacaoRoute
  '/alertas': typeof AlertasRouteWithChildren
  '/auditoria': typeof AuditoriaRoute
  '/criar-conta': typeof CriarContaRoute
  '/cvli-comparativo': typeof CvliComparativoRoute
  '/estatisticas': typeof EstatisticasRoute
  '/inqueritos': typeof InqueritosRouteWithChildren
  '/localidades': typeof LocalidadesRoute
  '/login': typeof LoginRoute
  '/modulos': typeof ModulosRoute
  '/nova-representacao': typeof NovaRepresentacaoRoute
  '/novo-caso': typeof NovoCasoRoute
  '/perfil': typeof PerfilRoute
  '/representacoes': typeof RepresentacoesRouteWithChildren
  '/admin/usuarios': typeof AdminUsuariosRouteWithChildren
  '/agenda/$agendamentoId': typeof AgendaAgendamentoIdRoute
  '/agenda/cronograma': typeof AgendaCronogramaRoute
  '/agenda/novo': typeof AgendaNovoRoute
  '/alertas/$modulo': typeof AlertasModuloRoute
  '/inqueritos/$caseId': typeof InqueritosCaseIdRouteWithChildren
  '/localizacao/enderecos': typeof LocalizacaoEnderecosRoute
  '/localizacao/pessoas': typeof LocalizacaoPessoasRoute
  '/localizacao/rotas': typeof LocalizacaoRotasRoute
  '/mockups/localizacao-operacional': typeof MockupsLocalizacaoOperacionalRoute
  '/objetos/$objectId': typeof ObjetosObjectIdRouteWithChildren
  '/objetos/novo': typeof ObjetosNovoRoute
  '/objetos/todos': typeof ObjetosTodosRoute
  '/representacoes/$representacaoId': typeof RepresentacoesRepresentacaoIdRouteWithChildren
  '/veiculos/$vehicleId': typeof VeiculosVehicleIdRouteWithChildren
  '/veiculos/adulterados': typeof VeiculosAdulteradosRoute
  '/veiculos/apreendidos': typeof VeiculosApreendidosRoute
  '/veiculos/automoveis': typeof VeiculosAutomoveisRoute
  '/veiculos/bicicletas': typeof VeiculosBicicletasRoute
  '/veiculos/caminhoes': typeof VeiculosCaminhoesRoute
  '/veiculos/liberados': typeof VeiculosLiberadosRoute
  '/veiculos/motocicletas': typeof VeiculosMotocicletasRoute
  '/veiculos/novo': typeof VeiculosNovoRoute
  '/veiculos/onibus': typeof VeiculosOnibusRoute
  '/veiculos/outros': typeof VeiculosOutrosRoute
  '/veiculos/recuperados': typeof VeiculosRecuperadosRoute
  '/veiculos/relatorios': typeof VeiculosRelatoriosRoute
  '/veiculos/todos': typeof VeiculosTodosRoute
  '/agenda': typeof AgendaIndexRoute
  '/localizacao': typeof LocalizacaoIndexRoute
  '/objetos': typeof ObjetosIndexRoute
  '/veiculos': typeof VeiculosIndexRoute
  '/admin/usuarios/$userId': typeof AdminUsuariosUserIdRoute
  '/agenda/editar/$agendamentoId': typeof AgendaEditarAgendamentoIdRoute
  '/inqueritos/$caseId/editar': typeof InqueritosCaseIdEditarRoute
  '/objetos/$objectId/editar': typeof ObjetosObjectIdEditarRoute
  '/representacoes/$representacaoId/editar': typeof RepresentacoesRepresentacaoIdEditarRoute
  '/veiculos/$vehicleId/editar': typeof VeiculosVehicleIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRouteWithChildren
  '/aguardando-autorizacao': typeof AguardandoAutorizacaoRoute
  '/alertas': typeof AlertasRouteWithChildren
  '/auditoria': typeof AuditoriaRoute
  '/criar-conta': typeof CriarContaRoute
  '/cvli-comparativo': typeof CvliComparativoRoute
  '/estatisticas': typeof EstatisticasRoute
  '/inqueritos': typeof InqueritosRouteWithChildren
  '/localidades': typeof LocalidadesRoute
  '/localizacao': typeof LocalizacaoRouteWithChildren
  '/login': typeof LoginRoute
  '/modulos': typeof ModulosRoute
  '/nova-representacao': typeof NovaRepresentacaoRoute
  '/novo-caso': typeof NovoCasoRoute
  '/objetos': typeof ObjetosRouteWithChildren
  '/perfil': typeof PerfilRoute
  '/representacoes': typeof RepresentacoesRouteWithChildren
  '/veiculos': typeof VeiculosRouteWithChildren
  '/admin/usuarios': typeof AdminUsuariosRouteWithChildren
  '/agenda/$agendamentoId': typeof AgendaAgendamentoIdRoute
  '/agenda/cronograma': typeof AgendaCronogramaRoute
  '/agenda/novo': typeof AgendaNovoRoute
  '/alertas/$modulo': typeof AlertasModuloRoute
  '/inqueritos/$caseId': typeof InqueritosCaseIdRouteWithChildren
  '/localizacao/enderecos': typeof LocalizacaoEnderecosRoute
  '/localizacao/pessoas': typeof LocalizacaoPessoasRoute
  '/localizacao/rotas': typeof LocalizacaoRotasRoute
  '/mockups/localizacao-operacional': typeof MockupsLocalizacaoOperacionalRoute
  '/objetos/$objectId': typeof ObjetosObjectIdRouteWithChildren
  '/objetos/novo': typeof ObjetosNovoRoute
  '/objetos/todos': typeof ObjetosTodosRoute
  '/representacoes/$representacaoId': typeof RepresentacoesRepresentacaoIdRouteWithChildren
  '/veiculos/$vehicleId': typeof VeiculosVehicleIdRouteWithChildren
  '/veiculos/adulterados': typeof VeiculosAdulteradosRoute
  '/veiculos/apreendidos': typeof VeiculosApreendidosRoute
  '/veiculos/automoveis': typeof VeiculosAutomoveisRoute
  '/veiculos/bicicletas': typeof VeiculosBicicletasRoute
  '/veiculos/caminhoes': typeof VeiculosCaminhoesRoute
  '/veiculos/liberados': typeof VeiculosLiberadosRoute
  '/veiculos/motocicletas': typeof VeiculosMotocicletasRoute
  '/veiculos/novo': typeof VeiculosNovoRoute
  '/veiculos/onibus': typeof VeiculosOnibusRoute
  '/veiculos/outros': typeof VeiculosOutrosRoute
  '/veiculos/recuperados': typeof VeiculosRecuperadosRoute
  '/veiculos/relatorios': typeof VeiculosRelatoriosRoute
  '/veiculos/todos': typeof VeiculosTodosRoute
  '/agenda/': typeof AgendaIndexRoute
  '/localizacao/': typeof LocalizacaoIndexRoute
  '/objetos/': typeof ObjetosIndexRoute
  '/veiculos/': typeof VeiculosIndexRoute
  '/admin/usuarios/$userId': typeof AdminUsuariosUserIdRoute
  '/agenda/editar/$agendamentoId': typeof AgendaEditarAgendamentoIdRoute
  '/inqueritos/$caseId/editar': typeof InqueritosCaseIdEditarRoute
  '/objetos/$objectId/editar': typeof ObjetosObjectIdEditarRoute
  '/representacoes/$representacaoId/editar': typeof RepresentacoesRepresentacaoIdEditarRoute
  '/veiculos/$vehicleId/editar': typeof VeiculosVehicleIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/aguardando-autorizacao'
    | '/alertas'
    | '/auditoria'
    | '/criar-conta'
    | '/cvli-comparativo'
    | '/estatisticas'
    | '/inqueritos'
    | '/localidades'
    | '/localizacao'
    | '/login'
    | '/modulos'
    | '/nova-representacao'
    | '/novo-caso'
    | '/objetos'
    | '/perfil'
    | '/representacoes'
    | '/veiculos'
    | '/admin/usuarios'
    | '/agenda/$agendamentoId'
    | '/agenda/cronograma'
    | '/agenda/novo'
    | '/alertas/$modulo'
    | '/inqueritos/$caseId'
    | '/localizacao/enderecos'
    | '/localizacao/pessoas'
    | '/localizacao/rotas'
    | '/mockups/localizacao-operacional'
    | '/objetos/$objectId'
    | '/objetos/novo'
    | '/objetos/todos'
    | '/representacoes/$representacaoId'
    | '/veiculos/$vehicleId'
    | '/veiculos/adulterados'
    | '/veiculos/apreendidos'
    | '/veiculos/automoveis'
    | '/veiculos/bicicletas'
    | '/veiculos/caminhoes'
    | '/veiculos/liberados'
    | '/veiculos/motocicletas'
    | '/veiculos/novo'
    | '/veiculos/onibus'
    | '/veiculos/outros'
    | '/veiculos/recuperados'
    | '/veiculos/relatorios'
    | '/veiculos/todos'
    | '/agenda/'
    | '/localizacao/'
    | '/objetos/'
    | '/veiculos/'
    | '/admin/usuarios/$userId'
    | '/agenda/editar/$agendamentoId'
    | '/inqueritos/$caseId/editar'
    | '/objetos/$objectId/editar'
    | '/representacoes/$representacaoId/editar'
    | '/veiculos/$vehicleId/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aguardando-autorizacao'
    | '/alertas'
    | '/auditoria'
    | '/criar-conta'
    | '/cvli-comparativo'
    | '/estatisticas'
    | '/inqueritos'
    | '/localidades'
    | '/login'
    | '/modulos'
    | '/nova-representacao'
    | '/novo-caso'
    | '/perfil'
    | '/representacoes'
    | '/admin/usuarios'
    | '/agenda/$agendamentoId'
    | '/agenda/cronograma'
    | '/agenda/novo'
    | '/alertas/$modulo'
    | '/inqueritos/$caseId'
    | '/localizacao/enderecos'
    | '/localizacao/pessoas'
    | '/localizacao/rotas'
    | '/mockups/localizacao-operacional'
    | '/objetos/$objectId'
    | '/objetos/novo'
    | '/objetos/todos'
    | '/representacoes/$representacaoId'
    | '/veiculos/$vehicleId'
    | '/veiculos/adulterados'
    | '/veiculos/apreendidos'
    | '/veiculos/automoveis'
    | '/veiculos/bicicletas'
    | '/veiculos/caminhoes'
    | '/veiculos/liberados'
    | '/veiculos/motocicletas'
    | '/veiculos/novo'
    | '/veiculos/onibus'
    | '/veiculos/outros'
    | '/veiculos/recuperados'
    | '/veiculos/relatorios'
    | '/veiculos/todos'
    | '/agenda'
    | '/localizacao'
    | '/objetos'
    | '/veiculos'
    | '/admin/usuarios/$userId'
    | '/agenda/editar/$agendamentoId'
    | '/inqueritos/$caseId/editar'
    | '/objetos/$objectId/editar'
    | '/representacoes/$representacaoId/editar'
    | '/veiculos/$vehicleId/editar'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/aguardando-autorizacao'
    | '/alertas'
    | '/auditoria'
    | '/criar-conta'
    | '/cvli-comparativo'
    | '/estatisticas'
    | '/inqueritos'
    | '/localidades'
    | '/localizacao'
    | '/login'
    | '/modulos'
    | '/nova-representacao'
    | '/novo-caso'
    | '/objetos'
    | '/perfil'
    | '/representacoes'
    | '/veiculos'
    | '/admin/usuarios'
    | '/agenda/$agendamentoId'
    | '/agenda/cronograma'
    | '/agenda/novo'
    | '/alertas/$modulo'
    | '/inqueritos/$caseId'
    | '/localizacao/enderecos'
    | '/localizacao/pessoas'
    | '/localizacao/rotas'
    | '/mockups/localizacao-operacional'
    | '/objetos/$objectId'
    | '/objetos/novo'
    | '/objetos/todos'
    | '/representacoes/$representacaoId'
    | '/veiculos/$vehicleId'
    | '/veiculos/adulterados'
    | '/veiculos/apreendidos'
    | '/veiculos/automoveis'
    | '/veiculos/bicicletas'
    | '/veiculos/caminhoes'
    | '/veiculos/liberados'
    | '/veiculos/motocicletas'
    | '/veiculos/novo'
    | '/veiculos/onibus'
    | '/veiculos/outros'
    | '/veiculos/recuperados'
    | '/veiculos/relatorios'
    | '/veiculos/todos'
    | '/agenda/'
    | '/localizacao/'
    | '/objetos/'
    | '/veiculos/'
    | '/admin/usuarios/$userId'
    | '/agenda/editar/$agendamentoId'
    | '/inqueritos/$caseId/editar'
    | '/objetos/$objectId/editar'
    | '/representacoes/$representacaoId/editar'
    | '/veiculos/$vehicleId/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRouteWithChildren
  AguardandoAutorizacaoRoute: typeof AguardandoAutorizacaoRoute
  AlertasRoute: typeof AlertasRouteWithChildren
  AuditoriaRoute: typeof AuditoriaRoute
  CriarContaRoute: typeof CriarContaRoute
  CvliComparativoRoute: typeof CvliComparativoRoute
  EstatisticasRoute: typeof EstatisticasRoute
  InqueritosRoute: typeof InqueritosRouteWithChildren
  LocalidadesRoute: typeof LocalidadesRoute
  LocalizacaoRoute: typeof LocalizacaoRouteWithChildren
  LoginRoute: typeof LoginRoute
  ModulosRoute: typeof ModulosRoute
  NovaRepresentacaoRoute: typeof NovaRepresentacaoRoute
  NovoCasoRoute: typeof NovoCasoRoute
  ObjetosRoute: typeof ObjetosRouteWithChildren
  PerfilRoute: typeof PerfilRoute
  RepresentacoesRoute: typeof RepresentacoesRouteWithChildren
  VeiculosRoute: typeof VeiculosRouteWithChildren
  AdminUsuariosRoute: typeof AdminUsuariosRouteWithChildren
  MockupsLocalizacaoOperacionalRoute: typeof MockupsLocalizacaoOperacionalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aguardando-autorizacao': {
      id: '/aguardando-autorizacao'
      path: '/aguardando-autorizacao'
      fullPath: '/aguardando-autorizacao'
      preLoaderRoute: typeof AguardandoAutorizacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertas': {
      id: '/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditoria': {
      id: '/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar-conta': {
      id: '/criar-conta'
      path: '/criar-conta'
      fullPath: '/criar-conta'
      preLoaderRoute: typeof CriarContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cvli-comparativo': {
      id: '/cvli-comparativo'
      path: '/cvli-comparativo'
      fullPath: '/cvli-comparativo'
      preLoaderRoute: typeof CvliComparativoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estatisticas': {
      id: '/estatisticas'
      path: '/estatisticas'
      fullPath: '/estatisticas'
      preLoaderRoute: typeof EstatisticasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inqueritos': {
      id: '/inqueritos'
      path: '/inqueritos'
      fullPath: '/inqueritos'
      preLoaderRoute: typeof InqueritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/localidades': {
      id: '/localidades'
      path: '/localidades'
      fullPath: '/localidades'
      preLoaderRoute: typeof LocalidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/localizacao': {
      id: '/localizacao'
      path: '/localizacao'
      fullPath: '/localizacao'
      preLoaderRoute: typeof LocalizacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modulos': {
      id: '/modulos'
      path: '/modulos'
      fullPath: '/modulos'
      preLoaderRoute: typeof ModulosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova-representacao': {
      id: '/nova-representacao'
      path: '/nova-representacao'
      fullPath: '/nova-representacao'
      preLoaderRoute: typeof NovaRepresentacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novo-caso': {
      id: '/novo-caso'
      path: '/novo-caso'
      fullPath: '/novo-caso'
      preLoaderRoute: typeof NovoCasoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objetos': {
      id: '/objetos'
      path: '/objetos'
      fullPath: '/objetos'
      preLoaderRoute: typeof ObjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/representacoes': {
      id: '/representacoes'
      path: '/representacoes'
      fullPath: '/representacoes'
      preLoaderRoute: typeof RepresentacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/veiculos': {
      id: '/veiculos'
      path: '/veiculos'
      fullPath: '/veiculos'
      preLoaderRoute: typeof VeiculosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda/': {
      id: '/agenda/'
      path: '/'
      fullPath: '/agenda/'
      preLoaderRoute: typeof AgendaIndexRouteImport
      parentRoute: typeof AgendaRoute
    }
    '/agenda/$agendamentoId': {
      id: '/agenda/$agendamentoId'
      path: '/$agendamentoId'
      fullPath: '/agenda/$agendamentoId'
      preLoaderRoute: typeof AgendaAgendamentoIdRouteImport
      parentRoute: typeof AgendaRoute
    }
    '/agenda/cronograma': {
      id: '/agenda/cronograma'
      path: '/cronograma'
      fullPath: '/agenda/cronograma'
      preLoaderRoute: typeof AgendaCronogramaRouteImport
      parentRoute: typeof AgendaRoute
    }
    '/agenda/novo': {
      id: '/agenda/novo'
      path: '/novo'
      fullPath: '/agenda/novo'
      preLoaderRoute: typeof AgendaNovoRouteImport
      parentRoute: typeof AgendaRoute
    }
    '/alertas/$modulo': {
      id: '/alertas/$modulo'
      path: '/$modulo'
      fullPath: '/alertas/$modulo'
      preLoaderRoute: typeof AlertasModuloRouteImport
      parentRoute: typeof AlertasRoute
    }
    '/inqueritos/$caseId': {
      id: '/inqueritos/$caseId'
      path: '/$caseId'
      fullPath: '/inqueritos/$caseId'
      preLoaderRoute: typeof InqueritosCaseIdRouteImport
      parentRoute: typeof InqueritosRoute
    }
    '/localizacao/': {
      id: '/localizacao/'
      path: '/'
      fullPath: '/localizacao/'
      preLoaderRoute: typeof LocalizacaoIndexRouteImport
      parentRoute: typeof LocalizacaoRoute
    }
    '/localizacao/enderecos': {
      id: '/localizacao/enderecos'
      path: '/enderecos'
      fullPath: '/localizacao/enderecos'
      preLoaderRoute: typeof LocalizacaoEnderecosRouteImport
      parentRoute: typeof LocalizacaoRoute
    }
    '/localizacao/pessoas': {
      id: '/localizacao/pessoas'
      path: '/pessoas'
      fullPath: '/localizacao/pessoas'
      preLoaderRoute: typeof LocalizacaoPessoasRouteImport
      parentRoute: typeof LocalizacaoRoute
    }
    '/localizacao/rotas': {
      id: '/localizacao/rotas'
      path: '/rotas'
      fullPath: '/localizacao/rotas'
      preLoaderRoute: typeof LocalizacaoRotasRouteImport
      parentRoute: typeof LocalizacaoRoute
    }
    '/mockups/localizacao-operacional': {
      id: '/mockups/localizacao-operacional'
      path: '/mockups/localizacao-operacional'
      fullPath: '/mockups/localizacao-operacional'
      preLoaderRoute: typeof MockupsLocalizacaoOperacionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objetos/': {
      id: '/objetos/'
      path: '/'
      fullPath: '/objetos/'
      preLoaderRoute: typeof ObjetosIndexRouteImport
      parentRoute: typeof ObjetosRoute
    }
    '/objetos/$objectId': {
      id: '/objetos/$objectId'
      path: '/$objectId'
      fullPath: '/objetos/$objectId'
      preLoaderRoute: typeof ObjetosObjectIdRouteImport
      parentRoute: typeof ObjetosRoute
    }
    '/objetos/novo': {
      id: '/objetos/novo'
      path: '/novo'
      fullPath: '/objetos/novo'
      preLoaderRoute: typeof ObjetosNovoRouteImport
      parentRoute: typeof ObjetosRoute
    }
    '/objetos/todos': {
      id: '/objetos/todos'
      path: '/todos'
      fullPath: '/objetos/todos'
      preLoaderRoute: typeof ObjetosTodosRouteImport
      parentRoute: typeof ObjetosRoute
    }
    '/representacoes/$representacaoId': {
      id: '/representacoes/$representacaoId'
      path: '/$representacaoId'
      fullPath: '/representacoes/$representacaoId'
      preLoaderRoute: typeof RepresentacoesRepresentacaoIdRouteImport
      parentRoute: typeof RepresentacoesRoute
    }
    '/veiculos/': {
      id: '/veiculos/'
      path: '/'
      fullPath: '/veiculos/'
      preLoaderRoute: typeof VeiculosIndexRouteImport
      parentRoute: typeof VeiculosRoute
    }
    '/veiculos/$vehicleId': {
      id: '/veiculos/$vehicleId'
      path: '/$vehicleId'
      fullPath: '/veiculos/$vehicleId'
      preLoaderRoute: typeof VeiculosVehicleIdRouteImport
      parentRoute: typeof VeiculosRoute
    }
    '/veiculos/adulterados': {
      id: '/veiculos/adulterados'
      path: '/adulterados'
      fullPath: '/veiculos/adulterados'
      preLoaderRoute: typeof VeiculosAdulteradosRouteImport
      parentRoute: typeof VeiculosRoute
    }
    '/veiculos/apreendidos': {
      id: '/veiculos/apreendidos'
      path: '/apreendidos'
      fullPath: '/veiculos/apreendidos'
      preLoaderRoute: typeof VeiculosApreendidosRouteImport
      parentRoute: typeof VeiculosRoute
    }
    '/veiculos/automoveis': {
      id: '/veiculos/automoveis'
      path: '/automoveis'
      fullPath: '/veiculos/automoveis'
      preLoaderRoute: typeof VeiculosAutomoveisRouteImport
      parentRoute: typeof VeiculosRoute
    }
    '/veiculos/bicicletas': {
      id: '/veiculos/bicicletas'
      path: '/bicicletas'
      fullPath: '/veiculos/bicicletas'
      preLoaderRoute: typeof VeiculosBicicletasRouteImport
      parentRoute: typeof VeiculosRoute
    }
    '/veiculos/caminhoes': {
      id: '/veiculos/caminhoes'
      path: '/caminhoes'
      fullPath: '/veiculos/caminhoes'
      preLoaderRoute: typeof VeiculosCaminhoesRouteImport
      parentRoute: typeof VeiculosRoute
    }
    '/veiculos/liberados': {
      id: '/veiculos/liberados'
      path: '/liberados'
      fullPath: '/veiculos/liberados'
      preLoaderRoute: typeof VeiculosLiberadosRouteImport
      parentRoute: typeof VeiculosRoute
    }
    '/veiculos/motocicletas': {
      id: '/veiculos/motocicletas'
      path: '/motocicletas'
      fullPath: '/veiculos/motocicletas'
      preLoaderRoute: typeof VeiculosMotocicletasRouteImport
      parentRoute: typeof VeiculosRoute
    }
    '/veiculos/novo': {
      id: '/veiculos/novo'
      path: '/novo'
      fullPath: '/veiculos/novo'
      preLoaderRoute: typeof VeiculosNovoRouteImport
      parentRoute: typeof VeiculosRoute
    }
    '/veiculos/onibus': {
      id: '/veiculos/onibus'
      path: '/onibus'
      fullPath: '/veiculos/onibus'
      preLoaderRoute: typeof VeiculosOnibusRouteImport
      parentRoute: typeof VeiculosRoute
    }
    '/veiculos/outros': {
      id: '/veiculos/outros'
      path: '/outros'
      fullPath: '/veiculos/outros'
      preLoaderRoute: typeof VeiculosOutrosRouteImport
      parentRoute: typeof VeiculosRoute
    }
    '/veiculos/recuperados': {
      id: '/veiculos/recuperados'
      path: '/recuperados'
      fullPath: '/veiculos/recuperados'
      preLoaderRoute: typeof VeiculosRecuperadosRouteImport
      parentRoute: typeof VeiculosRoute
    }
    '/veiculos/relatorios': {
      id: '/veiculos/relatorios'
      path: '/relatorios'
      fullPath: '/veiculos/relatorios'
      preLoaderRoute: typeof VeiculosRelatoriosRouteImport
      parentRoute: typeof VeiculosRoute
    }
    '/veiculos/todos': {
      id: '/veiculos/todos'
      path: '/todos'
      fullPath: '/veiculos/todos'
      preLoaderRoute: typeof VeiculosTodosRouteImport
      parentRoute: typeof VeiculosRoute
    }
    '/admin/usuarios/$userId': {
      id: '/admin/usuarios/$userId'
      path: '/$userId'
      fullPath: '/admin/usuarios/$userId'
      preLoaderRoute: typeof AdminUsuariosUserIdRouteImport
      parentRoute: typeof AdminUsuariosRoute
    }
    '/agenda/editar/$agendamentoId': {
      id: '/agenda/editar/$agendamentoId'
      path: '/editar/$agendamentoId'
      fullPath: '/agenda/editar/$agendamentoId'
      preLoaderRoute: typeof AgendaEditarAgendamentoIdRouteImport
      parentRoute: typeof AgendaRoute
    }
    '/inqueritos/$caseId/editar': {
      id: '/inqueritos/$caseId/editar'
      path: '/editar'
      fullPath: '/inqueritos/$caseId/editar'
      preLoaderRoute: typeof InqueritosCaseIdEditarRouteImport
      parentRoute: typeof InqueritosCaseIdRoute
    }
    '/objetos/$objectId/editar': {
      id: '/objetos/$objectId/editar'
      path: '/editar'
      fullPath: '/objetos/$objectId/editar'
      preLoaderRoute: typeof ObjetosObjectIdEditarRouteImport
      parentRoute: typeof ObjetosObjectIdRoute
    }
    '/representacoes/$representacaoId/editar': {
      id: '/representacoes/$representacaoId/editar'
      path: '/editar'
      fullPath: '/representacoes/$representacaoId/editar'
      preLoaderRoute: typeof RepresentacoesRepresentacaoIdEditarRouteImport
      parentRoute: typeof RepresentacoesRepresentacaoIdRoute
    }
    '/veiculos/$vehicleId/editar': {
      id: '/veiculos/$vehicleId/editar'
      path: '/editar'
      fullPath: '/veiculos/$vehicleId/editar'
      preLoaderRoute: typeof VeiculosVehicleIdEditarRouteImport
      parentRoute: typeof VeiculosVehicleIdRoute
    }
  }
}

interface AgendaRouteChildren {
  AgendaAgendamentoIdRoute: typeof AgendaAgendamentoIdRoute
  AgendaCronogramaRoute: typeof AgendaCronogramaRoute
  AgendaNovoRoute: typeof AgendaNovoRoute
  AgendaIndexRoute: typeof AgendaIndexRoute
  AgendaEditarAgendamentoIdRoute: typeof AgendaEditarAgendamentoIdRoute
}

const AgendaRouteChildren: AgendaRouteChildren = {
  AgendaAgendamentoIdRoute: AgendaAgendamentoIdRoute,
  AgendaCronogramaRoute: AgendaCronogramaRoute,
  AgendaNovoRoute: AgendaNovoRoute,
  AgendaIndexRoute: AgendaIndexRoute,
  AgendaEditarAgendamentoIdRoute: AgendaEditarAgendamentoIdRoute,
}

const AgendaRouteWithChildren =
  AgendaRoute._addFileChildren(AgendaRouteChildren)

interface AlertasRouteChildren {
  AlertasModuloRoute: typeof AlertasModuloRoute
}

const AlertasRouteChildren: AlertasRouteChildren = {
  AlertasModuloRoute: AlertasModuloRoute,
}

const AlertasRouteWithChildren =
  AlertasRoute._addFileChildren(AlertasRouteChildren)

interface InqueritosCaseIdRouteChildren {
  InqueritosCaseIdEditarRoute: typeof InqueritosCaseIdEditarRoute
}

const InqueritosCaseIdRouteChildren: InqueritosCaseIdRouteChildren = {
  InqueritosCaseIdEditarRoute: InqueritosCaseIdEditarRoute,
}

const InqueritosCaseIdRouteWithChildren =
  InqueritosCaseIdRoute._addFileChildren(InqueritosCaseIdRouteChildren)

interface InqueritosRouteChildren {
  InqueritosCaseIdRoute: typeof InqueritosCaseIdRouteWithChildren
}

const InqueritosRouteChildren: InqueritosRouteChildren = {
  InqueritosCaseIdRoute: InqueritosCaseIdRouteWithChildren,
}

const InqueritosRouteWithChildren = InqueritosRoute._addFileChildren(
  InqueritosRouteChildren,
)

interface LocalizacaoRouteChildren {
  LocalizacaoEnderecosRoute: typeof LocalizacaoEnderecosRoute
  LocalizacaoPessoasRoute: typeof LocalizacaoPessoasRoute
  LocalizacaoRotasRoute: typeof LocalizacaoRotasRoute
  LocalizacaoIndexRoute: typeof LocalizacaoIndexRoute
}

const LocalizacaoRouteChildren: LocalizacaoRouteChildren = {
  LocalizacaoEnderecosRoute: LocalizacaoEnderecosRoute,
  LocalizacaoPessoasRoute: LocalizacaoPessoasRoute,
  LocalizacaoRotasRoute: LocalizacaoRotasRoute,
  LocalizacaoIndexRoute: LocalizacaoIndexRoute,
}

const LocalizacaoRouteWithChildren = LocalizacaoRoute._addFileChildren(
  LocalizacaoRouteChildren,
)

interface ObjetosObjectIdRouteChildren {
  ObjetosObjectIdEditarRoute: typeof ObjetosObjectIdEditarRoute
}

const ObjetosObjectIdRouteChildren: ObjetosObjectIdRouteChildren = {
  ObjetosObjectIdEditarRoute: ObjetosObjectIdEditarRoute,
}

const ObjetosObjectIdRouteWithChildren = ObjetosObjectIdRoute._addFileChildren(
  ObjetosObjectIdRouteChildren,
)

interface ObjetosRouteChildren {
  ObjetosObjectIdRoute: typeof ObjetosObjectIdRouteWithChildren
  ObjetosNovoRoute: typeof ObjetosNovoRoute
  ObjetosTodosRoute: typeof ObjetosTodosRoute
  ObjetosIndexRoute: typeof ObjetosIndexRoute
}

const ObjetosRouteChildren: ObjetosRouteChildren = {
  ObjetosObjectIdRoute: ObjetosObjectIdRouteWithChildren,
  ObjetosNovoRoute: ObjetosNovoRoute,
  ObjetosTodosRoute: ObjetosTodosRoute,
  ObjetosIndexRoute: ObjetosIndexRoute,
}

const ObjetosRouteWithChildren =
  ObjetosRoute._addFileChildren(ObjetosRouteChildren)

interface RepresentacoesRepresentacaoIdRouteChildren {
  RepresentacoesRepresentacaoIdEditarRoute: typeof RepresentacoesRepresentacaoIdEditarRoute
}

const RepresentacoesRepresentacaoIdRouteChildren: RepresentacoesRepresentacaoIdRouteChildren =
  {
    RepresentacoesRepresentacaoIdEditarRoute:
      RepresentacoesRepresentacaoIdEditarRoute,
  }

const RepresentacoesRepresentacaoIdRouteWithChildren =
  RepresentacoesRepresentacaoIdRoute._addFileChildren(
    RepresentacoesRepresentacaoIdRouteChildren,
  )

interface RepresentacoesRouteChildren {
  RepresentacoesRepresentacaoIdRoute: typeof RepresentacoesRepresentacaoIdRouteWithChildren
}

const RepresentacoesRouteChildren: RepresentacoesRouteChildren = {
  RepresentacoesRepresentacaoIdRoute:
    RepresentacoesRepresentacaoIdRouteWithChildren,
}

const RepresentacoesRouteWithChildren = RepresentacoesRoute._addFileChildren(
  RepresentacoesRouteChildren,
)

interface VeiculosVehicleIdRouteChildren {
  VeiculosVehicleIdEditarRoute: typeof VeiculosVehicleIdEditarRoute
}

const VeiculosVehicleIdRouteChildren: VeiculosVehicleIdRouteChildren = {
  VeiculosVehicleIdEditarRoute: VeiculosVehicleIdEditarRoute,
}

const VeiculosVehicleIdRouteWithChildren =
  VeiculosVehicleIdRoute._addFileChildren(VeiculosVehicleIdRouteChildren)

interface VeiculosRouteChildren {
  VeiculosVehicleIdRoute: typeof VeiculosVehicleIdRouteWithChildren
  VeiculosAdulteradosRoute: typeof VeiculosAdulteradosRoute
  VeiculosApreendidosRoute: typeof VeiculosApreendidosRoute
  VeiculosAutomoveisRoute: typeof VeiculosAutomoveisRoute
  VeiculosBicicletasRoute: typeof VeiculosBicicletasRoute
  VeiculosCaminhoesRoute: typeof VeiculosCaminhoesRoute
  VeiculosLiberadosRoute: typeof VeiculosLiberadosRoute
  VeiculosMotocicletasRoute: typeof VeiculosMotocicletasRoute
  VeiculosNovoRoute: typeof VeiculosNovoRoute
  VeiculosOnibusRoute: typeof VeiculosOnibusRoute
  VeiculosOutrosRoute: typeof VeiculosOutrosRoute
  VeiculosRecuperadosRoute: typeof VeiculosRecuperadosRoute
  VeiculosRelatoriosRoute: typeof VeiculosRelatoriosRoute
  VeiculosTodosRoute: typeof VeiculosTodosRoute
  VeiculosIndexRoute: typeof VeiculosIndexRoute
}

const VeiculosRouteChildren: VeiculosRouteChildren = {
  VeiculosVehicleIdRoute: VeiculosVehicleIdRouteWithChildren,
  VeiculosAdulteradosRoute: VeiculosAdulteradosRoute,
  VeiculosApreendidosRoute: VeiculosApreendidosRoute,
  VeiculosAutomoveisRoute: VeiculosAutomoveisRoute,
  VeiculosBicicletasRoute: VeiculosBicicletasRoute,
  VeiculosCaminhoesRoute: VeiculosCaminhoesRoute,
  VeiculosLiberadosRoute: VeiculosLiberadosRoute,
  VeiculosMotocicletasRoute: VeiculosMotocicletasRoute,
  VeiculosNovoRoute: VeiculosNovoRoute,
  VeiculosOnibusRoute: VeiculosOnibusRoute,
  VeiculosOutrosRoute: VeiculosOutrosRoute,
  VeiculosRecuperadosRoute: VeiculosRecuperadosRoute,
  VeiculosRelatoriosRoute: VeiculosRelatoriosRoute,
  VeiculosTodosRoute: VeiculosTodosRoute,
  VeiculosIndexRoute: VeiculosIndexRoute,
}

const VeiculosRouteWithChildren = VeiculosRoute._addFileChildren(
  VeiculosRouteChildren,
)

interface AdminUsuariosRouteChildren {
  AdminUsuariosUserIdRoute: typeof AdminUsuariosUserIdRoute
}

const AdminUsuariosRouteChildren: AdminUsuariosRouteChildren = {
  AdminUsuariosUserIdRoute: AdminUsuariosUserIdRoute,
}

const AdminUsuariosRouteWithChildren = AdminUsuariosRoute._addFileChildren(
  AdminUsuariosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRouteWithChildren,
  AguardandoAutorizacaoRoute: AguardandoAutorizacaoRoute,
  AlertasRoute: AlertasRouteWithChildren,
  AuditoriaRoute: AuditoriaRoute,
  CriarContaRoute: CriarContaRoute,
  CvliComparativoRoute: CvliComparativoRoute,
  EstatisticasRoute: EstatisticasRoute,
  InqueritosRoute: InqueritosRouteWithChildren,
  LocalidadesRoute: LocalidadesRoute,
  LocalizacaoRoute: LocalizacaoRouteWithChildren,
  LoginRoute: LoginRoute,
  ModulosRoute: ModulosRoute,
  NovaRepresentacaoRoute: NovaRepresentacaoRoute,
  NovoCasoRoute: NovoCasoRoute,
  ObjetosRoute: ObjetosRouteWithChildren,
  PerfilRoute: PerfilRoute,
  RepresentacoesRoute: RepresentacoesRouteWithChildren,
  VeiculosRoute: VeiculosRouteWithChildren,
  AdminUsuariosRoute: AdminUsuariosRouteWithChildren,
  MockupsLocalizacaoOperacionalRoute: MockupsLocalizacaoOperacionalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
