/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RepresentacoesRouteImport } from './routes/representacoes'
import { Route as NovoCasoRouteImport } from './routes/novo-caso'
import { Route as ModulosRouteImport } from './routes/modulos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminUsuariosUserIdRouteImport } from './routes/admin.usuarios.$userId'
import { Route as RepresentacoesRepresentacaoIdEditarRouteImport } from './routes/representacoes.$representacaoId.editar'
import { Route as RepresentacoesRepresentacaoIdRouteImport } from './routes/representacoes.$representacaoId'
import { Route as NovaRepresentacaoRouteImport } from './routes/nova-representacao'
import { Route as InqueritosEditarRouteImport } from './routes/inqueritos.$caseId.editar'
import { Route as InqueritosCaseIdRouteImport } from './routes/inqueritos.$caseId'
import { Route as InqueritosRouteImport } from './routes/inqueritos'
import { Route as AuditoriaRouteImport } from './routes/auditoria'
import { Route as AlertasRouteImport } from './routes/alertas'
import { Route as IndexRouteImport } from './routes/index'

const RepresentacoesRoute = RepresentacoesRouteImport.update({
  id: '/representacoes',
  path: '/representacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const RepresentacoesRepresentacaoIdRoute =
  RepresentacoesRepresentacaoIdRouteImport.update({
    id: '/$representacaoId',
    path: '/$representacaoId',
    getParentRoute: () => RepresentacoesRoute,
  } as any)
const RepresentacoesRepresentacaoIdEditarRoute =
  RepresentacoesRepresentacaoIdEditarRouteImport.update({
    id: '/editar',
    path: '/editar',
    getParentRoute: () => RepresentacoesRepresentacaoIdRoute,
  } as any)
const NovoCasoRoute = NovoCasoRouteImport.update({
  id: '/novo-caso',
  path: '/novo-caso',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulosRoute = ModulosRouteImport.update({
  id: '/modulos',
  path: '/modulos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/admin/usuarios',
  path: '/admin/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsuariosUserIdRoute = AdminUsuariosUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AdminUsuariosRoute,
} as any)
const NovaRepresentacaoRoute = NovaRepresentacaoRouteImport.update({
  id: '/nova-representacao',
  path: '/nova-representacao',
  getParentRoute: () => rootRouteImport,
} as any)
const InqueritosRoute = InqueritosRouteImport.update({
  id: '/inqueritos',
  path: '/inqueritos',
  getParentRoute: () => rootRouteImport,
} as any)
const InqueritosCaseIdRoute = InqueritosCaseIdRouteImport.update({
  id: '/$caseId',
  path: '/$caseId',
  getParentRoute: () => InqueritosRoute,
} as any)
const InqueritosEditarRoute = InqueritosEditarRouteImport.update({
  id: '/editar',
  path: '/editar',
  getParentRoute: () => InqueritosCaseIdRoute,
} as any)
const AuditoriaRoute = AuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertasRoute = AlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/usuarios/$userId': typeof AdminUsuariosUserIdRoute
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/auditoria': typeof AuditoriaRoute
  '/inqueritos': typeof InqueritosRoute
  '/inqueritos/$caseId': typeof InqueritosCaseIdRoute
  '/inqueritos/$caseId/editar': typeof InqueritosEditarRoute
  '/login': typeof LoginRoute
  '/modulos': typeof ModulosRoute
  '/novo-caso': typeof NovoCasoRoute
  '/nova-representacao': typeof NovaRepresentacaoRoute
  '/representacoes': typeof RepresentacoesRoute
  '/representacoes/$representacaoId': typeof RepresentacoesRepresentacaoIdRoute
  '/representacoes/$representacaoId/editar': typeof RepresentacoesRepresentacaoIdEditarRoute
}
export interface FileRoutesByTo {
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/usuarios/$userId': typeof AdminUsuariosUserIdRoute
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/auditoria': typeof AuditoriaRoute
  '/inqueritos': typeof InqueritosRoute
  '/inqueritos/$caseId': typeof InqueritosCaseIdRoute
  '/inqueritos/$caseId/editar': typeof InqueritosEditarRoute
  '/login': typeof LoginRoute
  '/modulos': typeof ModulosRoute
  '/novo-caso': typeof NovoCasoRoute
  '/nova-representacao': typeof NovaRepresentacaoRoute
  '/representacoes': typeof RepresentacoesRoute
  '/representacoes/$representacaoId': typeof RepresentacoesRepresentacaoIdRoute
  '/representacoes/$representacaoId/editar': typeof RepresentacoesRepresentacaoIdEditarRoute
}
export interface FileRoutesById {
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/usuarios/$userId': typeof AdminUsuariosUserIdRoute
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/auditoria': typeof AuditoriaRoute
  '/inqueritos': typeof InqueritosRoute
  '/inqueritos/$caseId': typeof InqueritosCaseIdRoute
  '/inqueritos/$caseId/editar': typeof InqueritosEditarRoute
  '/login': typeof LoginRoute
  '/modulos': typeof ModulosRoute
  '/novo-caso': typeof NovoCasoRoute
  '/nova-representacao': typeof NovaRepresentacaoRoute
  '/representacoes': typeof RepresentacoesRoute
  '/representacoes/$representacaoId': typeof RepresentacoesRepresentacaoIdRoute
  '/representacoes/$representacaoId/editar': typeof RepresentacoesRepresentacaoIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alertas'
    | '/admin/usuarios'
    | '/admin/usuarios/$userId'
    | '/admin/usuarios'
    | '/admin/usuarios/$userId'
    | '/admin/usuarios'
    | '/admin/usuarios/$userId'
    | '/auditoria'
    | '/inqueritos'
    | '/inqueritos/$caseId'
    | '/inqueritos/$caseId/editar'
    | '/login'
    | '/modulos'
    | '/novo-caso'
    | '/nova-representacao'
    | '/representacoes'
    | '/representacoes/$representacaoId'
    | '/representacoes/$representacaoId/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alertas'
    | '/admin/usuarios'
    | '/admin/usuarios/$userId'
    | '/admin/usuarios'
    | '/admin/usuarios/$userId'
    | '/auditoria'
    | '/inqueritos'
    | '/inqueritos/$caseId'
    | '/inqueritos/$caseId/editar'
    | '/login'
    | '/modulos'
    | '/novo-caso'
    | '/nova-representacao'
    | '/representacoes'
    | '/representacoes/$representacaoId'
    | '/representacoes/$representacaoId/editar'
  id:
    | '__root__'
    | '/'
    | '/alertas'
    | '/admin/usuarios'
    | '/admin/usuarios/$userId'
    | '/admin/usuarios'
    | '/admin/usuarios/$userId'
    | '/auditoria'
    | '/inqueritos'
    | '/inqueritos/$caseId'
    | '/inqueritos/$caseId/editar'
    | '/login'
    | '/modulos'
    | '/novo-caso'
    | '/nova-representacao'
    | '/representacoes'
    | '/representacoes/$representacaoId'
    | '/representacoes/$representacaoId/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertasRoute: typeof AlertasRoute
  AdminUsuariosRoute: typeof AdminUsuariosRouteWithChildren
  AuditoriaRoute: typeof AuditoriaRoute
  InqueritosRoute: typeof InqueritosRoute
  LoginRoute: typeof LoginRoute
  ModulosRoute: typeof ModulosRoute
  NovoCasoRoute: typeof NovoCasoRoute
  NovaRepresentacaoRoute: typeof NovaRepresentacaoRoute
  RepresentacoesRoute: typeof RepresentacoesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/representacoes': {
      id: '/representacoes'
      path: '/representacoes'
      fullPath: '/representacoes'
      preLoaderRoute: typeof RepresentacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novo-caso': {
      id: '/novo-caso'
      path: '/novo-caso'
      fullPath: '/novo-caso'
      preLoaderRoute: typeof NovoCasoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova-representacao': {
      id: '/nova-representacao'
      path: '/nova-representacao'
      fullPath: '/nova-representacao'
      preLoaderRoute: typeof NovaRepresentacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/representacoes/$representacaoId': {
      id: '/representacoes/$representacaoId'
      path: '/$representacaoId'
      fullPath: '/representacoes/$representacaoId'
      preLoaderRoute: typeof RepresentacoesRepresentacaoIdRouteImport
      parentRoute: typeof RepresentacoesRoute
    }
    '/representacoes/$representacaoId/editar': {
      id: '/representacoes/$representacaoId/editar'
      path: '/editar'
      fullPath: '/representacoes/$representacaoId/editar'
      preLoaderRoute: typeof RepresentacoesRepresentacaoIdEditarRouteImport
      parentRoute: typeof RepresentacoesRepresentacaoIdRoute
    }
    '/modulos': {
      id: '/modulos'
      path: '/modulos'
      fullPath: '/modulos'
      preLoaderRoute: typeof ModulosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }

    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usuarios/$userId': {
      id: '/admin/usuarios/$userId'
      path: '/$userId'
      fullPath: '/admin/usuarios/$userId'
      preLoaderRoute: typeof AdminUsuariosUserIdRouteImport
      parentRoute: typeof AdminUsuariosRoute
    }
    '/inqueritos': {
      id: '/inqueritos'
      path: '/inqueritos'
      fullPath: '/inqueritos'
      preLoaderRoute: typeof InqueritosRouteImport
      parentRoute: typeof rootRouteImport
    }

    '/inqueritos/$caseId': {
      id: '/inqueritos/$caseId'
      path: '/$caseId'
      fullPath: '/inqueritos/$caseId'
      preLoaderRoute: typeof InqueritosCaseIdRouteImport
      parentRoute: typeof InqueritosRoute
    }
    '/inqueritos/$caseId/editar': {
      id: '/inqueritos/$caseId/editar'
      path: '/editar'
      fullPath: '/inqueritos/$caseId/editar'
      preLoaderRoute: typeof InqueritosEditarRouteImport
      parentRoute: typeof InqueritosCaseIdRoute
    }
    '/auditoria': {
      id: '/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertas': {
      id: '/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}


const AdminUsuariosRouteChildren = {
  AdminUsuariosUserIdRoute: AdminUsuariosUserIdRoute,
}

const AdminUsuariosRouteWithChildren =
  AdminUsuariosRoute._addFileChildren(AdminUsuariosRouteChildren)

const RepresentacoesRepresentacaoIdRouteChildren = {
  RepresentacoesRepresentacaoIdEditarRoute: RepresentacoesRepresentacaoIdEditarRoute,
}

const RepresentacoesRepresentacaoIdRouteWithChildren =
  RepresentacoesRepresentacaoIdRoute._addFileChildren(
    RepresentacoesRepresentacaoIdRouteChildren,
  )

const RepresentacoesRouteChildren = {
  RepresentacoesRepresentacaoIdRoute: RepresentacoesRepresentacaoIdRouteWithChildren,
}

const RepresentacoesRouteWithChildren =
  RepresentacoesRoute._addFileChildren(RepresentacoesRouteChildren)

const InqueritosCaseIdRouteChildren = {
  InqueritosEditarRoute: InqueritosEditarRoute,
}

const InqueritosCaseIdRouteWithChildren = InqueritosCaseIdRoute._addFileChildren(
  InqueritosCaseIdRouteChildren,
)

const InqueritosRouteChildren = {
  InqueritosCaseIdRoute: InqueritosCaseIdRouteWithChildren,
}

const InqueritosRouteWithChildren = InqueritosRoute._addFileChildren(
  InqueritosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertasRoute: AlertasRoute,
  AdminUsuariosRoute: AdminUsuariosRouteWithChildren,
  AuditoriaRoute: AuditoriaRoute,
  InqueritosRoute: InqueritosRouteWithChildren,
  LoginRoute: LoginRoute,
  ModulosRoute: ModulosRoute,
  NovoCasoRoute: NovoCasoRoute,
  NovaRepresentacaoRoute: NovaRepresentacaoRoute,
  RepresentacoesRoute: RepresentacoesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
